Umbraco-test-src/Models/NavigationLink.cs
namespace Umbraco_test_src.Models
{
    public class NavigationLink
    {
        public string Text { get; set; }

        public string Url { get; set; }

        public bool NewWindow { get; set; }

        public string Target
        {
            get { return NewWindow ? "_blank" : null; }
        }

        public string Title { get; set; }

        public NavigationLink()
        {
        }

        public NavigationLink(string url, string text = null, bool newWindow = false, string title = null)
        {
            Url = url;
            Text = text;
            NewWindow = newWindow;
            Title = title;
        }
    }
}

Umbraco-test-src/Models/NavigationListItem.cs
using System.Collections.Generic;
using System.Linq;

namespace Umbraco_test_src.Models
{
    public class NavigationListItem
    {
        public string Text { get; set; }

        public NavigationLink Link { get; set; }

        public List<NavigationListItem> Items { get; set; }

        public bool HasChildred
        {
            get { return Items != null && Items.Any(); }
        }

        public NavigationListItem()
        {
        }

        public NavigationListItem(NavigationLink link)
        {
            Link = link;
        }

        public NavigationListItem(string text)
        {
            Text = text;
        }
    }
}

Umbraco-test-src/Controllers/HomeController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace Umbraco_test_src.Controllers
{
    public class HomeController : SurfaceController
    {
        private const string PartialViewFolder = "~/Views/Partials/Home/";

        public ActionResult RenderFeatured()
        {
            return PartialView($"{PartialViewFolder}_Featured.cshtml");
        }

        public ActionResult RenderServices()
        {
            return PartialView($"{PartialViewFolder}_Services.cshtml");
        }

        public ActionResult RenderBlog()
        {
            return PartialView($"{PartialViewFolder}_Blog.cshtml");
        }

        public ActionResult RenderClients()
        {
            return PartialView($"{PartialViewFolder}_Clients.cshtml");
        }
    }
}

Umbraco-test-src/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Caching;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco_test_src.Models;
using Umbraco.Web;

namespace Umbraco_test_src.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PartialViewFolder = "~/Views/Partials/SiteLayout/";


        public ActionResult RenderHeader()
        {
            List<NavigationListItem> nav = GetObjectFromCache("mainNav", 5, GetNavigationModelFromDatabase);
            return PartialView($"{PartialViewFolder}_Header.cshtml", nav);
        }

        public ActionResult RenderFooter()
        {
            return PartialView($"{ PartialViewFolder }_Footer.cshtml");
        }

        public ActionResult RenderIntro()
        {
            return PartialView($"{PartialViewFolder}_Intro.cshtml");
        }

        public ActionResult RenderTitleControls()
        {
            return PartialView($"{PartialViewFolder}_TitleControls.cshtml");
        }

        #region Navigation

        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {
            //const int HomePositionInPath = 1;
            //int homePageId = int.Parse(CurrentPage.Path.Split(',')[HomePositionInPath]);
            //IPublishedContent homePage = Umbraco.Content(homePageId);
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            List<NavigationListItem> nav = new List<NavigationListItem>();
            nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItem> GetChildNavigationList(IPublishedContent page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible");
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach (var childPage in childPages)
                {
                    NavigationListItem listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }

        private static T GetObjectFromCache<T>(string cacheItemName, int cacheTimeInMinutes, Func<T> objectSettingFunction)
        {
            ObjectCache cache = MemoryCache.Default;
            var cachedObject = (T)cache[cacheItemName];

            if (cachedObject == null)
            {
                var policy = new CacheItemPolicy();
                policy.AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(cacheTimeInMinutes);
                cachedObject = objectSettingFunction();
                cache.Set(cacheItemName, cachedObject, policy);
            }

            return cachedObject;
        }



        #endregion
    }
}

Umbraco-test-src/Views/Blog.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-blog-section">
    <div class="container">
        @{ Html.RenderAction("RenderTitleControls", "SiteLayout"); }
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="blog-inner">
                    <a href="#"><img class="img-responsive" src="/images/image_4.jpg" alt="Blog"></a>
                    <div class="desc">
                        <h3><a href="#">New iPhone 6 Released</a></h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                        <p><a href="#" class="btn btn-primary btn-outline with-arrow">Read More<i class="icon-arrow-right"></i></a></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-inner">
                            <a href="#"><img class="img-responsive" src="/images/image_7.jpg" alt="Blog"></a>
                            <div class="desc">
                                <h3><a href="#">New iPhone 6 Released</a></h3>
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                                <p><a href="#" class="btn btn-primary btn-outline with-arrow">Read More<i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="blog-inner">
                    <a href="#"><img class="img-responsive" src="/images/image_5.jpg" alt="Blog"></a>
                    <div class="desc">
                        <h3><a href="#">Beans</a></h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                        <p><a href="#" class="btn btn-primary btn-outline with-arrow">Read More<i class="icon-arrow-right"></i></a></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-inner">
                            <a href="#"><img class="img-responsive" src="/images/image_9.jpg" alt="Blog"></a>
                            <div class="desc">
                                <h3><a href="#">New iPhone 6 Released</a></h3>
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                                <p><a href="#" class="btn btn-primary btn-outline with-arrow">Read More<i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="blog-inner">
                    <a href="#"><img class="img-responsive" src="/images/image_6.jpg" alt="Blog"></a>
                    <div class="desc">
                        <h3><a href="#">Bookmarksgrove right</a></h3>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                        <p><a href="#" class="btn btn-primary btn-outline with-arrow">Read More<i class="icon-arrow-right"></i></a></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="blog-inner">
                            <a href="#"><img class="img-responsive" src="/images/image_10.jpg" alt="Blog"></a>
                            <div class="desc">
                                <h3><a href="#">New iPhone 6 Released</a></h3>
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                                <p><a href="#" class="btn btn-primary btn-outline with-arrow">Read More<i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	</div>

Umbraco-test-src/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-contact-section">
    <div class="container">
        @{ Html.RenderAction("RenderTitleControls", "SiteLayout"); }
        <div class="row">
            <div class="col-md-3">
                <h3>Contact Info.</h3>
                <ul class="contact-info">
                    <li><i class="sl-icon-map"></i>198 West 21th Street, Suite 721 New York NY 10016</li>
                    <li><i class="sl-icon-phone"></i>+ 1235 2355 98</li>
                    <li><i class="sl-icon-envelope-open"></i><a href="#">info@yoursite.com</a></li>
                    <li><i class="sl-icon-globe-alt"></i><a href="#">www.yoursite.com</a></li>
                </ul>
            </div>
            <div class="col-md-8 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input class="form-control" placeholder="Name" type="text">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input class="form-control" placeholder="Email" type="text">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <textarea name="" class="form-control" id="" cols="30" rows="7" placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <input value="Send Message" class="btn btn-primary" type="submit">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="map" data-animate-effect="fadeIn"></div>

@section ScriptsBottom
{
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCefOgb1ZWqYtj7raVSmN4PL2WkTrc-KyA&sensor=false"></script>
    <script src="~/Scripts/google_map.js"></script>
}

Umbraco-test-src/Views/Content.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-about-section">
		<div class="container">
            @{ Html.RenderAction("RenderTitleControls", "SiteLayout"); }
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-12">
							<div class="about-inner">
								<img class="img-responsive" src="/images/image_about.jpg" alt="About">
								<h3>History</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
								<blockquote>
									<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
								</blockquote>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<aside class="sidebar">
						<div class="row">
							<div class="col-md-12 side">
								<h3>Categories</h3>
								<ul>
									<li><i class="icon-check"></i><a href="#">Web Design</a></li>
									<li><i class="icon-check"></i><a href="#">Branding &amp; Identity</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5</a></li>
									<li><i class="icon-check"></i><a href="#">HandCrafted Templates</a></li>
									<li><i class="icon-check"></i><a href="#">Free Bootstrap Template</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5 Template</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5 &amp; CSS3 Template</a></li>
									<li><i class="icon-check"></i><a href="#">HandCrafted Templates</a></li>
								</ul>
							</div>
							<div class="col-md-12 side">
								<h3>Paragraph</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
							</div>
						</div>
					</aside>
				</div>
			</div>
		</div>
	</div>

Umbraco-test-src/Views/Home1.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderIntro", "SiteLayout"); }
@{ Html.RenderAction("RenderFeatured", "Home"); }
@{ Html.RenderAction("RenderServices", "Home"); }
@{ Html.RenderAction("RenderBlog", "Home"); }
@{ Html.RenderAction("RenderClients", "Home"); }

Umbraco-test-src/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Umbraco-test-src/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Umbraco-test-src/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

Umbraco-test-src/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Umbraco-test-src/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

Umbraco-test-src/Views/Portfolio.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

	<div id="fh5co-work-section">
        <div class="container">
            @{ Html.RenderAction("RenderTitleControls", "SiteLayout"); }
            <div class="row">
                <div class="col-md-4 text-center">
                    <div class="work-inner">
                        <a href="#" class="work-grid" style="background-image: url(/images/image_1.jpg);">
                        </a>
                        <div class="desc">
                            <h3><a href="#">Work with love</a></h3>
                            <span>Web Design</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="work-inner">
                        <a href="#" class="work-grid" style="background-image: url(/images/image_2.jpg);">
                        </a>
                        <div class="desc">
                            <h3><a href="#">Work with love</a></h3>
                            <span>Web Design</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="work-inner">
                        <a href="#" class="work-grid" style="background-image: url(/images/image_3.jpg);">
                        </a>
                        <div class="desc">
                            <h3><a href="#">Work with love</a></h3>
                            <span>Web Design</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="work-inner">
                        <a href="#" class="work-grid" style="background-image: url(/images/image_4.jpg);">
                        </a>
                        <div class="desc">
                            <h3><a href="#">Work with love</a></h3>
                            <span>Web Design</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="work-inner">
                        <a href="#" class="work-grid" style="background-image: url(/images/image_5.jpg);">
                        </a>
                        <div class="desc">
                            <h3><a href="#">Work with love</a></h3>
                            <span>Web Design</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="work-inner">
                        <a href="#" class="work-grid" style="background-image: url(/images/image_6.jpg);">
                        </a>
                        <div class="desc">
                            <h3><a href="#">Work with love</a></h3>
                            <span>Web Design</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>

Umbraco-test-src/Views/Services.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-main-services-section">
		<div class="container">
            @{ Html.RenderAction("RenderTitleControls", "SiteLayout"); }
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-12 services-inner">
							<span><i class="sl-icon-graph"></i></span>
							<div class="desc">
								<h3>Finance Dashboard</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
							</div>
						<div class="col-md-12 services-inner">
							<span><i class="sl-icon-heart"></i></span>
							<div class="desc">
								<h3>Made with Love</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
						<div class="col-md-12 services-inner">
							<span><i class="sl-icon-key"></i></span>
							<div class="desc">
								<h3>Help &amp; Support</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<aside class="sidebar">
						<div class="row">
							<div class="col-md-12 side">
								<h3>Categories</h3>
								<ul>
									<li><i class="icon-check"></i><a href="#">Web Design</a></li>
									<li><i class="icon-check"></i><a href="#">Branding &amp; Identity</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5</a></li>
									<li><i class="icon-check"></i><a href="#">HandCrafted Templates</a></li>
									<li><i class="icon-check"></i><a href="#">Free Bootstrap Template</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5 Template</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5 &amp; CSS3 Template</a></li>
									<li><i class="icon-check"></i><a href="#">HandCrafted Templates</a></li>
								</ul>
							</div>
							<div class="col-md-12 side">
								<h3>Paragraph</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
							</div>
						</div>
					</aside>
				</div>
			</div>
		</div>
	</div>

Umbraco-test-src/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Optimization

@{
    Layout = null;
}

@* the fun starts here *@


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lesser &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />
    <!--
      //////////////////////////////////////////////////////

      FREE HTML5 TEMPLATE
      DESIGNED & DEVELOPED by FreeHTML5.co

      Website: 		http://freehtml5.co/
      Email: 			info@freehtml5.co
      Twitter: 		http://twitter.com/fh5co
      Facebook: 		https://www.facebook.com/fh5co

      //////////////////////////////////////////////////////
       -->
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700,900' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="/css/icomoon.css">
    <!-- Simple Line Icons -->
    <link rel="stylesheet" href="/css/simple-line-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- Modernizr JS -->
    <script src="/Scripts/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    @RenderSection("Head", required: false)
</head>
<body>
    @RenderSection("ScriptsTop", required: false)

    <div id="fh5co-page">
        @{ Html.RenderAction("RenderHeader", "SiteLayout"); }

        @RenderBody()

        @{ Html.RenderAction("RenderFooter", "SiteLayout"); }}
    </div>


    <!-- jQuery -->
    <script src="/Scripts/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="/Scripts/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="/Scripts/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="/Scripts/jquery.waypoints.min.js"></script>

    @RenderSection("ScriptsBottom", required: false)

    <!-- MAIN JS -->
    <script src="/Scripts/main.js"></script>
</body>
</html>